<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ProjectDigitization.Engine-4d645fc8-8622-4cb8-befc-901d9304d228</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectDigitization.DataAccess\ProjectDigitization.DataAccess.csproj" />
    <ProjectReference Include="..\ProjectDigitization.Interfaces\ProjectDigitization.Interfaces.csproj" />
    <ProjectReference Include="..\ProjectDigitization.Services\ProjectDigitization.Services.csproj" />
    <ProjectReference Include="..\ProjectDigitization.ViewModels\ProjectDigitization.ViewModels.csproj" />
  </ItemGroup>
</Project>
