CREATE TABLE [dbo].[UserRole]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[UserTypeId] UNIQUEIDENTIFIER NOT NULL,
	[CreatedBy] NVARCHAR(50) NULL,
	[CreatedOn] DATETIME2 NULL,
	[LastModifiedBy] NVARCHAR(50) NULL,
	[LastModifiedOn] DATETIME2 NULL,
	CONSTRAINT [PK_UserRoleID] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_UserRole_UserID] FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users]([Id]),
	CONSTRAINT [FK_UserRole_UserTypeID] FOREIGN KEY ([UserTypeId]) REFERENCES [dbo].[UserTypes]([Id])
)
