CREATE TABLE [dbo].[UserTypes]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[CreatedBy] NVARCHAR(50) NULL,
	[CreatedOn] DATETIME2 NULL,
	[LastModifiedBy] NVARCHAR(50) NULL,
	[LastModifiedOn] DATETIME2 NULL,
	CONSTRAINT [PK_UserTypeID] PRIMARY KEY CLUSTERED ([Id] ASC)
)
