CREATE TABLE [dbo].[Users]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[UserId] NVARCHAR(50) NOT NULL,
	[UserName] NVARCHAR(100) NOT NULL,
	[UserTypeId] UNIQUEIDENTIFIER NOT NULL,
	[CreatedBy] NVARCHAR(50) NULL,
	[CreatedOn] DATETIME2 NULL,
	[LastModifiedBy] NVARCHAR(50) NULL,
	[LastModifiedOn] DATETIME2 NULL
	CONSTRAINT [PK_UserID] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_User_UserTypeID] FOREIGN KEY ([UserTypeId]) REFERENCES [dbo].[UserTypes]([Id])
)
